Add date-time validation
dapryor/question-framework pull request #6
Opened 2020-10-13 07:55 UTC by Sabreen-Parveen

- [ ] Contains functions which check date and time

2020-10-13 20:11 UTC, dapryor commented
Hey @Sabreen-Parveen

Thanks for the PR!

a few things:
1.  Since these are meant to be validations for some input, I think there should not be an optional required argument. It should always be required.

1. I have updated in the interface I am trying to maintain for validators in the issue for #3 .  If you could check that out and update you code, that would be appreciated.

1.  I would prefer to stick to functions only instead of classes.

1.  I think the more preferred approach here would be to make a function factory that allowed a user to specify a datetime string to validate against and if the user wanted to convert that to a datetime object, a post_processor could be used.

2020-10-13 20:36 UTC, Sabreen-Parveen commented
Sure, I would modify my PR

2020-10-15 01:37 UTC, dapryor requested changes

2020-10-15 01:37 UTC, dapryor commented on question_framework/validation/validation.py
> +  date_format = '%Y-%m-%d'
Hardcoding the date format limits the number of scenarios you can use this validation.

I think you should make this a function factory that takes a date format and creates/returns a function that utilizes that format to determine if the input is correctly formatted. The return function should take in a string and output a bool.

This function from the function factory should ONLY return  True or False. 

There are some examples of a function factory in the validation.py file.

2020-10-15 01:37 UTC, dapryor commented on question_framework/validation/validation.py
> +    return(date_obj)
validation functions should only return True or False

2020-10-15 01:37 UTC, dapryor commented on question_framework/validation/validation.py
> +    return "Invalid date format, it should be 'yyyy-mm-dd'"
validation functions should only return True or False

2020-10-15 01:37 UTC, dapryor commented on question_framework/validation/validation.py
> +    date_obj = datetime.strptime(x, date_format)
try checking out this stack overflow for ways to validate
https://stackoverflow.com/questions/16870663/how-do-i-validate-a-date-string-format-in-python/16870682

2020-10-15 04:44 UTC, Sabreen-Parveen commented on question_framework/validation/validation.py
> +    date_obj = datetime.strptime(x, date_format)
I will correct it.

2020-10-16 17:52 UTC, Sabreen-Parveen commented
I have made changes. Please review my PR

2020-10-16 18:16 UTC, dapryor commented
Hey @Sabreen-Parveen 
It seems your function still does not allow for dynamic datetime patterns to be used.  I would like to see a function factory similar to the x_hex_character_validation_gen.

Also you will need to rebase your code so we can merge it AND write a few test for your function

2020-10-21 03:05 UTC, closed without merging